# Generated by Django 3.1.6 on 2021-02-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutMe', models.CharField(blank=True, max_length=255, null=True, verbose_name='About me')),
                ('userStatus', models.CharField(blank=True, max_length=255, null=True, verbose_name='User status')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='User job')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('feedName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ribbon name')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('my_site', models.URLField(blank=True, max_length=255, null=True)),
                ('vk', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('you_tube', models.URLField(blank=True, max_length=255, null=True)),
                ('git_hub', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
