# Generated by Django 3.1.6 on 2021-02-27 20:19

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('tags', models.TextField(verbose_name='Тэги')),
                ('image', models.ImageField(upload_to=users.models.upload_path_handler, verbose_name='Изображение')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser', verbose_name='Автор')),
            ],
        ),
    ]
