# Generated by Django 3.1.6 on 2021-02-27 20:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path_handler, verbose_name='Изображение'),
        ),
    ]
