# Generated by Django 3.1.6 on 2021-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210227_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
