# Generated by Django 3.1.6 on 2021-03-01 04:36

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path_handler, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.CreateModel(
            name='AvatarPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_path_for_avatar, verbose_name='Avatar')),
                ('imgURL', models.URLField(blank=True, max_length=255, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser', verbose_name='Author')),
            ],
        ),
    ]
