# Generated by Django 3.1.6 on 2021-03-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210301_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvatarPhoto',
            new_name='AvatarBackgroundPhoto',
        ),
    ]
