# Generated by Django 3.1.6 on 2021-03-06 22:18

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210306_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.upload_path_for_avatar, verbose_name='Background')),
                ('imgURL', models.URLField(blank=True, max_length=255, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser', verbose_name='Author')),
            ],
        ),
    ]
