# Generated by Django 3.1.6 on 2021-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_backgroundphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=100, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='avatarURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
