# Generated by Django 3.1.6 on 2021-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags'),
        ),
    ]
