# Generated by Django 3.1.6 on 2021-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_backgroundurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='date_blocked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='State timer'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='valueOffline',
            field=models.IntegerField(default=5, verbose_name='Time in offline'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='valueOnline',
            field=models.IntegerField(default=20, verbose_name='Time in online'),
        ),
    ]
