# Generated by Django 3.1.6 on 2021-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210406_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='State app'),
        ),
    ]
