# Generated by Django 3.1.6 on 2021-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profileuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like count'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked app'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='date_blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Blocked timer'),
        ),
    ]
