# Generated by Django 3.1.6 on 2021-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
