# Generated by Django 3.1.6 on 2021-04-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_like_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatarURL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.avatarphoto', verbose_name='AvatarURL'),
        ),
    ]
