# Generated by Django 3.1.6 on 2021-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210413_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatarURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
