# Generated by Django 3.1.6 on 2021-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_profileuser_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='rest_of_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
