# Generated by Django 3.1.6 on 2021-05-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profileuser_rest_of_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='date_blocked',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='rest_of_time',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='valueOffline',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='valueOnline',
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueOnline', models.IntegerField(default=20, verbose_name='Time in online')),
                ('valueOffline', models.IntegerField(default=5, verbose_name='Time in offline')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked app')),
                ('date_blocked', models.DateTimeField(blank=True, null=True)),
                ('rest_of_time', models.DateTimeField(blank=True, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser', verbose_name='Author')),
            ],
        ),
    ]
