# Generated by Django 3.1.6 on 2021-05-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210508_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='valueOnline',
            field=models.IntegerField(default=40, verbose_name='Time in online'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Task')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profileuser', verbose_name='Author')),
            ],
        ),
    ]
